BDRSPS-545: Survey Occurance Data v1.0
gaiaresources/abis-mapping pull request #133
Opened 2024-04-11 03:23 UTC by chungvl

2024-04-11 05:09 UTC, joecrowleygaia requested changes
We don't have versioning for SSD yet. Please move all changes to the `survey_occurrence_data/` directory and resubmit.

2024-04-12 07:43 UTC, serge-gaia approved these changes

2024-04-12 07:43 UTC, serge-gaia commented on abis_mapping/templates/survey_occurrence_data/schema.json
> +      "type": "string",
type string but example shows a list type
also in incidental occurrences (V2) otherCatalogNumbers is a list.

2024-04-12 07:43 UTC, serge-gaia commented on abis_mapping/templates/survey_occurrence_data/schema.json
> +      "type": "string",
There are some mismatches between the schema of incidental and SSD shared fields.
Still merging that but created a ticket for harmonisation of the two schema

2024-04-12 07:44 UTC, serge-gaia commented
You need to approve @joecrowleygaia

2024-04-12 08:07 UTC, joecrowleygaia approved these changes

2024-04-12 08:10 UTC, merged