BDRSPS-764 Survey metadata v2 changelog
gaiaresources/abis-mapping pull request #239
Opened 2024-10-04 05:15 UTC by Lincoln-GR

2024-10-04 06:19 UTC, joecrowleygaia requested changes

2024-10-04 06:26 UTC, Lincoln-GR commented on docs/contexts/survey_metadata_v2.py
> +from abis_mapping.templates.survey_metadata_v2.mapping import SurveyMetadataMapper
oops yes you're right

2024-10-04 06:36 UTC, Lincoln-GR commented on docs/contexts/survey_metadata_v2.py
> +from abis_mapping.templates.survey_metadata_v2.mapping import SurveyMetadataMapper
fixed

2024-10-07 00:25 UTC, joecrowleygaia approved these changes

2024-10-07 00:25 UTC, merged