[BDRSPS-961] Updated `biodiversity_type` for systematic occurance templates
gaiaresources/abis-mapping pull request #291
Opened 2024-10-31 02:09 UTC by chungvl

2024-10-31 03:25 UTC, Lincoln-GR commented on abis_mapping/templates/survey_occurrence_data/metadata.json
> +    "biodiversity_type": "Systematic Species Occurrences",
"Systematic **Survey** Species Occurrences"?

2024-11-05 02:17 UTC, serge-gaia requested changes

2024-11-05 02:17 UTC, serge-gaia commented on abis_mapping/templates/survey_occurrence_data_v2/metadata.json
> +    "biodiversity_type": "Systematic Species Occurrences",
Systematic **Survey** Species Occurrences

2024-11-05 03:11 UTC, serge-gaia approved these changes

2024-11-05 03:12 UTC, merged